// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: dropshipbe.proto

package dropshipbe

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dropshipbe_GetInventory_FullMethodName                = "/dropshipbe.Dropshipbe/GetInventory"
	Dropshipbe_GetProducts_FullMethodName                 = "/dropshipbe.Dropshipbe/GetProducts"
	Dropshipbe_GetProductBySlug_FullMethodName            = "/dropshipbe.Dropshipbe/GetProductBySlug"
	Dropshipbe_GetProductsByCategory_FullMethodName       = "/dropshipbe.Dropshipbe/GetProductsByCategory"
	Dropshipbe_GetRelatedProducts_FullMethodName          = "/dropshipbe.Dropshipbe/GetRelatedProducts"
	Dropshipbe_GetFeaturedProducts_FullMethodName         = "/dropshipbe.Dropshipbe/GetFeaturedProducts"
	Dropshipbe_GetNewProducts_FullMethodName              = "/dropshipbe.Dropshipbe/GetNewProducts"
	Dropshipbe_CreateProduct_FullMethodName               = "/dropshipbe.Dropshipbe/CreateProduct"
	Dropshipbe_GetFrequentlyBoughtProducts_FullMethodName = "/dropshipbe.Dropshipbe/GetFrequentlyBoughtProducts"
	Dropshipbe_GetShop_FullMethodName                     = "/dropshipbe.Dropshipbe/GetShop"
	Dropshipbe_GetSocialProductVideos_FullMethodName      = "/dropshipbe.Dropshipbe/GetSocialProductVideos"
	Dropshipbe_GetProductFaqs_FullMethodName              = "/dropshipbe.Dropshipbe/GetProductFaqs"
	Dropshipbe_CreateProductFaq_FullMethodName            = "/dropshipbe.Dropshipbe/CreateProductFaq"
	Dropshipbe_GetProductReviews_FullMethodName           = "/dropshipbe.Dropshipbe/GetProductReviews"
	Dropshipbe_CreateProductReview_FullMethodName         = "/dropshipbe.Dropshipbe/CreateProductReview"
	Dropshipbe_GetSliderItems_FullMethodName              = "/dropshipbe.Dropshipbe/GetSliderItems"
	Dropshipbe_GetCategoryItems_FullMethodName            = "/dropshipbe.Dropshipbe/GetCategoryItems"
	Dropshipbe_GetBannerItems_FullMethodName              = "/dropshipbe.Dropshipbe/GetBannerItems"
	Dropshipbe_GetVideoBanner_FullMethodName              = "/dropshipbe.Dropshipbe/GetVideoBanner"
	Dropshipbe_GetBlogItems_FullMethodName                = "/dropshipbe.Dropshipbe/GetBlogItems"
	Dropshipbe_GetBlogBySlug_FullMethodName               = "/dropshipbe.Dropshipbe/GetBlogBySlug"
	Dropshipbe_CreateNewBlog_FullMethodName               = "/dropshipbe.Dropshipbe/CreateNewBlog"
	Dropshipbe_CreateOption_FullMethodName                = "/dropshipbe.Dropshipbe/CreateOption"
	Dropshipbe_CreateOptionValue_FullMethodName           = "/dropshipbe.Dropshipbe/CreateOptionValue"
	Dropshipbe_Login_FullMethodName                       = "/dropshipbe.Dropshipbe/Login"
	Dropshipbe_UploadFile_FullMethodName                  = "/dropshipbe.Dropshipbe/UploadFile"
	Dropshipbe_DeleteFile_FullMethodName                  = "/dropshipbe.Dropshipbe/DeleteFile"
	Dropshipbe_CreateOrder_FullMethodName                 = "/dropshipbe.Dropshipbe/CreateOrder"
	Dropshipbe_CaptureOrder_FullMethodName                = "/dropshipbe.Dropshipbe/CaptureOrder"
	Dropshipbe_HandlePaypalWebhook_FullMethodName         = "/dropshipbe.Dropshipbe/HandlePaypalWebhook"
	Dropshipbe_Ping_FullMethodName                        = "/dropshipbe.Dropshipbe/Ping"
	Dropshipbe_ChatbotMessage_FullMethodName              = "/dropshipbe.Dropshipbe/ChatbotMessage"
	Dropshipbe_GetGuestToken_FullMethodName               = "/dropshipbe.Dropshipbe/GetGuestToken"
)

// DropshipbeClient is the client API for Dropshipbe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DropshipbeClient interface {
	// --- Inventory ---
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error)
	// --- Products ---
	GetProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
	GetProductBySlug(ctx context.Context, in *GetProductBySlugRequest, opts ...grpc.CallOption) (*Product, error)
	GetProductsByCategory(ctx context.Context, in *GetProductsByCategoryRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
	GetRelatedProducts(ctx context.Context, in *GetRelatedProductsRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
	GetFeaturedProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
	GetNewProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error)
	GetFrequentlyBoughtProducts(ctx context.Context, in *GetFrequentlyBoughtProductsRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
	// --- Shop Search ---
	GetShop(ctx context.Context, in *ShopSearchParams, opts ...grpc.CallOption) (*ProductListResponse, error)
	// --- Media/Galleries ---
	GetSocialProductVideos(ctx context.Context, in *GetSocialProductVideoRequest, opts ...grpc.CallOption) (*GalleryListResponse, error)
	// --- FAQs ---
	GetProductFaqs(ctx context.Context, in *GetProductFaqsRequest, opts ...grpc.CallOption) (*FaqListResponse, error)
	CreateProductFaq(ctx context.Context, in *CreateProductFaqRequest, opts ...grpc.CallOption) (*Faq, error)
	// --- Reviews ---
	GetProductReviews(ctx context.Context, in *GetProductReviewsRequest, opts ...grpc.CallOption) (*ReviewSummary, error)
	CreateProductReview(ctx context.Context, in *CreateProductReviewRequest, opts ...grpc.CallOption) (*ReviewItem, error)
	// --- UI Items (Sliders, Categories, Banners) ---
	GetSliderItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*SliderListResponse, error)
	GetCategoryItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*CategoryListResponse, error)
	GetBannerItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*BannerListResponse, error)
	GetVideoBanner(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*Banner, error)
	// --- Blogs ---
	GetBlogItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*BlogListResponse, error)
	GetBlogBySlug(ctx context.Context, in *GetBlogBySlugRequest, opts ...grpc.CallOption) (*BlogDetailResponse, error)
	CreateNewBlog(ctx context.Context, in *CreateNewBlogRequest, opts ...grpc.CallOption) (*Blog, error)
	// --- Options ---
	CreateOption(ctx context.Context, in *CreateOptionRequest, opts ...grpc.CallOption) (*Option, error)
	CreateOptionValue(ctx context.Context, in *CreateOptionValueRequest, opts ...grpc.CallOption) (*OptionValue, error)
	// --- Authentication ---
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// --- Files ---
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	// --- Orders & Checkout ---
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	CaptureOrder(ctx context.Context, in *CaptureOrderRequest, opts ...grpc.CallOption) (*CaptureOrderResponse, error)
	// --- Webhooks () ---
	HandlePaypalWebhook(ctx context.Context, in *PayPalWebhookRequest, opts ...grpc.CallOption) (*WebhookResponse, error)
	// --- System ---
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// API  Chatbot AI
	ChatbotMessage(ctx context.Context, in *ChatbotRequest, opts ...grpc.CallOption) (*ChatbotResponse, error)
	// Guest token for chatbot
	GetGuestToken(ctx context.Context, in *GetGuestTokenRequest, opts ...grpc.CallOption) (*GetGuestTokenResponse, error)
}

type dropshipbeClient struct {
	cc grpc.ClientConnInterface
}

func NewDropshipbeClient(cc grpc.ClientConnInterface) DropshipbeClient {
	return &dropshipbeClient{cc}
}

func (c *dropshipbeClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetProductBySlug(ctx context.Context, in *GetProductBySlugRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, Dropshipbe_GetProductBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetProductsByCategory(ctx context.Context, in *GetProductsByCategoryRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetProductsByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetRelatedProducts(ctx context.Context, in *GetRelatedProductsRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetRelatedProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetFeaturedProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetFeaturedProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetNewProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetNewProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, Dropshipbe_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetFrequentlyBoughtProducts(ctx context.Context, in *GetFrequentlyBoughtProductsRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetFrequentlyBoughtProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetShop(ctx context.Context, in *ShopSearchParams, opts ...grpc.CallOption) (*ProductListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetSocialProductVideos(ctx context.Context, in *GetSocialProductVideoRequest, opts ...grpc.CallOption) (*GalleryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GalleryListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetSocialProductVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetProductFaqs(ctx context.Context, in *GetProductFaqsRequest, opts ...grpc.CallOption) (*FaqListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FaqListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetProductFaqs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) CreateProductFaq(ctx context.Context, in *CreateProductFaqRequest, opts ...grpc.CallOption) (*Faq, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Faq)
	err := c.cc.Invoke(ctx, Dropshipbe_CreateProductFaq_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetProductReviews(ctx context.Context, in *GetProductReviewsRequest, opts ...grpc.CallOption) (*ReviewSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewSummary)
	err := c.cc.Invoke(ctx, Dropshipbe_GetProductReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) CreateProductReview(ctx context.Context, in *CreateProductReviewRequest, opts ...grpc.CallOption) (*ReviewItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewItem)
	err := c.cc.Invoke(ctx, Dropshipbe_CreateProductReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetSliderItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*SliderListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SliderListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetSliderItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetCategoryItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*CategoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetCategoryItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetBannerItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*BannerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BannerListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetBannerItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetVideoBanner(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*Banner, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Banner)
	err := c.cc.Invoke(ctx, Dropshipbe_GetVideoBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetBlogItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*BlogListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlogListResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetBlogItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetBlogBySlug(ctx context.Context, in *GetBlogBySlugRequest, opts ...grpc.CallOption) (*BlogDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlogDetailResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetBlogBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) CreateNewBlog(ctx context.Context, in *CreateNewBlogRequest, opts ...grpc.CallOption) (*Blog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Blog)
	err := c.cc.Invoke(ctx, Dropshipbe_CreateNewBlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) CreateOption(ctx context.Context, in *CreateOptionRequest, opts ...grpc.CallOption) (*Option, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Option)
	err := c.cc.Invoke(ctx, Dropshipbe_CreateOption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) CreateOptionValue(ctx context.Context, in *CreateOptionValueRequest, opts ...grpc.CallOption) (*OptionValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptionValue)
	err := c.cc.Invoke(ctx, Dropshipbe_CreateOptionValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) CaptureOrder(ctx context.Context, in *CaptureOrderRequest, opts ...grpc.CallOption) (*CaptureOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureOrderResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_CaptureOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) HandlePaypalWebhook(ctx context.Context, in *PayPalWebhookRequest, opts ...grpc.CallOption) (*WebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_HandlePaypalWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Dropshipbe_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) ChatbotMessage(ctx context.Context, in *ChatbotRequest, opts ...grpc.CallOption) (*ChatbotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatbotResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_ChatbotMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropshipbeClient) GetGuestToken(ctx context.Context, in *GetGuestTokenRequest, opts ...grpc.CallOption) (*GetGuestTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGuestTokenResponse)
	err := c.cc.Invoke(ctx, Dropshipbe_GetGuestToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DropshipbeServer is the server API for Dropshipbe service.
// All implementations must embed UnimplementedDropshipbeServer
// for forward compatibility.
type DropshipbeServer interface {
	// --- Inventory ---
	GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error)
	// --- Products ---
	GetProducts(context.Context, *DefaultRequest) (*ProductListResponse, error)
	GetProductBySlug(context.Context, *GetProductBySlugRequest) (*Product, error)
	GetProductsByCategory(context.Context, *GetProductsByCategoryRequest) (*ProductListResponse, error)
	GetRelatedProducts(context.Context, *GetRelatedProductsRequest) (*ProductListResponse, error)
	GetFeaturedProducts(context.Context, *DefaultRequest) (*ProductListResponse, error)
	GetNewProducts(context.Context, *DefaultRequest) (*ProductListResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*Product, error)
	GetFrequentlyBoughtProducts(context.Context, *GetFrequentlyBoughtProductsRequest) (*ProductListResponse, error)
	// --- Shop Search ---
	GetShop(context.Context, *ShopSearchParams) (*ProductListResponse, error)
	// --- Media/Galleries ---
	GetSocialProductVideos(context.Context, *GetSocialProductVideoRequest) (*GalleryListResponse, error)
	// --- FAQs ---
	GetProductFaqs(context.Context, *GetProductFaqsRequest) (*FaqListResponse, error)
	CreateProductFaq(context.Context, *CreateProductFaqRequest) (*Faq, error)
	// --- Reviews ---
	GetProductReviews(context.Context, *GetProductReviewsRequest) (*ReviewSummary, error)
	CreateProductReview(context.Context, *CreateProductReviewRequest) (*ReviewItem, error)
	// --- UI Items (Sliders, Categories, Banners) ---
	GetSliderItems(context.Context, *DefaultRequest) (*SliderListResponse, error)
	GetCategoryItems(context.Context, *DefaultRequest) (*CategoryListResponse, error)
	GetBannerItems(context.Context, *DefaultRequest) (*BannerListResponse, error)
	GetVideoBanner(context.Context, *DefaultRequest) (*Banner, error)
	// --- Blogs ---
	GetBlogItems(context.Context, *DefaultRequest) (*BlogListResponse, error)
	GetBlogBySlug(context.Context, *GetBlogBySlugRequest) (*BlogDetailResponse, error)
	CreateNewBlog(context.Context, *CreateNewBlogRequest) (*Blog, error)
	// --- Options ---
	CreateOption(context.Context, *CreateOptionRequest) (*Option, error)
	CreateOptionValue(context.Context, *CreateOptionValueRequest) (*OptionValue, error)
	// --- Authentication ---
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// --- Files ---
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	// --- Orders & Checkout ---
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	CaptureOrder(context.Context, *CaptureOrderRequest) (*CaptureOrderResponse, error)
	// --- Webhooks () ---
	HandlePaypalWebhook(context.Context, *PayPalWebhookRequest) (*WebhookResponse, error)
	// --- System ---
	Ping(context.Context, *Request) (*Response, error)
	// API  Chatbot AI
	ChatbotMessage(context.Context, *ChatbotRequest) (*ChatbotResponse, error)
	// Guest token for chatbot
	GetGuestToken(context.Context, *GetGuestTokenRequest) (*GetGuestTokenResponse, error)
	mustEmbedUnimplementedDropshipbeServer()
}

// UnimplementedDropshipbeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDropshipbeServer struct{}

func (UnimplementedDropshipbeServer) GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedDropshipbeServer) GetProducts(context.Context, *DefaultRequest) (*ProductListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedDropshipbeServer) GetProductBySlug(context.Context, *GetProductBySlugRequest) (*Product, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductBySlug not implemented")
}
func (UnimplementedDropshipbeServer) GetProductsByCategory(context.Context, *GetProductsByCategoryRequest) (*ProductListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductsByCategory not implemented")
}
func (UnimplementedDropshipbeServer) GetRelatedProducts(context.Context, *GetRelatedProductsRequest) (*ProductListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelatedProducts not implemented")
}
func (UnimplementedDropshipbeServer) GetFeaturedProducts(context.Context, *DefaultRequest) (*ProductListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeaturedProducts not implemented")
}
func (UnimplementedDropshipbeServer) GetNewProducts(context.Context, *DefaultRequest) (*ProductListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewProducts not implemented")
}
func (UnimplementedDropshipbeServer) CreateProduct(context.Context, *CreateProductRequest) (*Product, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedDropshipbeServer) GetFrequentlyBoughtProducts(context.Context, *GetFrequentlyBoughtProductsRequest) (*ProductListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFrequentlyBoughtProducts not implemented")
}
func (UnimplementedDropshipbeServer) GetShop(context.Context, *ShopSearchParams) (*ProductListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShop not implemented")
}
func (UnimplementedDropshipbeServer) GetSocialProductVideos(context.Context, *GetSocialProductVideoRequest) (*GalleryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSocialProductVideos not implemented")
}
func (UnimplementedDropshipbeServer) GetProductFaqs(context.Context, *GetProductFaqsRequest) (*FaqListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductFaqs not implemented")
}
func (UnimplementedDropshipbeServer) CreateProductFaq(context.Context, *CreateProductFaqRequest) (*Faq, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductFaq not implemented")
}
func (UnimplementedDropshipbeServer) GetProductReviews(context.Context, *GetProductReviewsRequest) (*ReviewSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductReviews not implemented")
}
func (UnimplementedDropshipbeServer) CreateProductReview(context.Context, *CreateProductReviewRequest) (*ReviewItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductReview not implemented")
}
func (UnimplementedDropshipbeServer) GetSliderItems(context.Context, *DefaultRequest) (*SliderListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSliderItems not implemented")
}
func (UnimplementedDropshipbeServer) GetCategoryItems(context.Context, *DefaultRequest) (*CategoryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryItems not implemented")
}
func (UnimplementedDropshipbeServer) GetBannerItems(context.Context, *DefaultRequest) (*BannerListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBannerItems not implemented")
}
func (UnimplementedDropshipbeServer) GetVideoBanner(context.Context, *DefaultRequest) (*Banner, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideoBanner not implemented")
}
func (UnimplementedDropshipbeServer) GetBlogItems(context.Context, *DefaultRequest) (*BlogListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlogItems not implemented")
}
func (UnimplementedDropshipbeServer) GetBlogBySlug(context.Context, *GetBlogBySlugRequest) (*BlogDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlogBySlug not implemented")
}
func (UnimplementedDropshipbeServer) CreateNewBlog(context.Context, *CreateNewBlogRequest) (*Blog, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewBlog not implemented")
}
func (UnimplementedDropshipbeServer) CreateOption(context.Context, *CreateOptionRequest) (*Option, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOption not implemented")
}
func (UnimplementedDropshipbeServer) CreateOptionValue(context.Context, *CreateOptionValueRequest) (*OptionValue, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOptionValue not implemented")
}
func (UnimplementedDropshipbeServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedDropshipbeServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedDropshipbeServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedDropshipbeServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedDropshipbeServer) CaptureOrder(context.Context, *CaptureOrderRequest) (*CaptureOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptureOrder not implemented")
}
func (UnimplementedDropshipbeServer) HandlePaypalWebhook(context.Context, *PayPalWebhookRequest) (*WebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandlePaypalWebhook not implemented")
}
func (UnimplementedDropshipbeServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDropshipbeServer) ChatbotMessage(context.Context, *ChatbotRequest) (*ChatbotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatbotMessage not implemented")
}
func (UnimplementedDropshipbeServer) GetGuestToken(context.Context, *GetGuestTokenRequest) (*GetGuestTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGuestToken not implemented")
}
func (UnimplementedDropshipbeServer) mustEmbedUnimplementedDropshipbeServer() {}
func (UnimplementedDropshipbeServer) testEmbeddedByValue()                    {}

// UnsafeDropshipbeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DropshipbeServer will
// result in compilation errors.
type UnsafeDropshipbeServer interface {
	mustEmbedUnimplementedDropshipbeServer()
}

func RegisterDropshipbeServer(s grpc.ServiceRegistrar, srv DropshipbeServer) {
	// If the following call panics, it indicates UnimplementedDropshipbeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dropshipbe_ServiceDesc, srv)
}

func _Dropshipbe_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetProducts(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetProductBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetProductBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetProductBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetProductBySlug(ctx, req.(*GetProductBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetProductsByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetProductsByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetProductsByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetProductsByCategory(ctx, req.(*GetProductsByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetRelatedProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelatedProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetRelatedProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetRelatedProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetRelatedProducts(ctx, req.(*GetRelatedProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetFeaturedProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetFeaturedProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetFeaturedProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetFeaturedProducts(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetNewProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetNewProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetNewProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetNewProducts(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetFrequentlyBoughtProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFrequentlyBoughtProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetFrequentlyBoughtProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetFrequentlyBoughtProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetFrequentlyBoughtProducts(ctx, req.(*GetFrequentlyBoughtProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopSearchParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetShop(ctx, req.(*ShopSearchParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetSocialProductVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSocialProductVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetSocialProductVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetSocialProductVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetSocialProductVideos(ctx, req.(*GetSocialProductVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetProductFaqs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductFaqsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetProductFaqs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetProductFaqs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetProductFaqs(ctx, req.(*GetProductFaqsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_CreateProductFaq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductFaqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).CreateProductFaq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_CreateProductFaq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).CreateProductFaq(ctx, req.(*CreateProductFaqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetProductReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetProductReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetProductReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetProductReviews(ctx, req.(*GetProductReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_CreateProductReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).CreateProductReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_CreateProductReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).CreateProductReview(ctx, req.(*CreateProductReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetSliderItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetSliderItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetSliderItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetSliderItems(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetCategoryItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetCategoryItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetCategoryItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetCategoryItems(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetBannerItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetBannerItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetBannerItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetBannerItems(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetVideoBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetVideoBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetVideoBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetVideoBanner(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetBlogItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetBlogItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetBlogItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetBlogItems(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetBlogBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlogBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetBlogBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetBlogBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetBlogBySlug(ctx, req.(*GetBlogBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_CreateNewBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).CreateNewBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_CreateNewBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).CreateNewBlog(ctx, req.(*CreateNewBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_CreateOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).CreateOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_CreateOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).CreateOption(ctx, req.(*CreateOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_CreateOptionValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOptionValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).CreateOptionValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_CreateOptionValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).CreateOptionValue(ctx, req.(*CreateOptionValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_CaptureOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).CaptureOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_CaptureOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).CaptureOrder(ctx, req.(*CaptureOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_HandlePaypalWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayPalWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).HandlePaypalWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_HandlePaypalWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).HandlePaypalWebhook(ctx, req.(*PayPalWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_ChatbotMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatbotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).ChatbotMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_ChatbotMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).ChatbotMessage(ctx, req.(*ChatbotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropshipbe_GetGuestToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuestTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropshipbeServer).GetGuestToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropshipbe_GetGuestToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropshipbeServer).GetGuestToken(ctx, req.(*GetGuestTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dropshipbe_ServiceDesc is the grpc.ServiceDesc for Dropshipbe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dropshipbe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dropshipbe.Dropshipbe",
	HandlerType: (*DropshipbeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInventory",
			Handler:    _Dropshipbe_GetInventory_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _Dropshipbe_GetProducts_Handler,
		},
		{
			MethodName: "GetProductBySlug",
			Handler:    _Dropshipbe_GetProductBySlug_Handler,
		},
		{
			MethodName: "GetProductsByCategory",
			Handler:    _Dropshipbe_GetProductsByCategory_Handler,
		},
		{
			MethodName: "GetRelatedProducts",
			Handler:    _Dropshipbe_GetRelatedProducts_Handler,
		},
		{
			MethodName: "GetFeaturedProducts",
			Handler:    _Dropshipbe_GetFeaturedProducts_Handler,
		},
		{
			MethodName: "GetNewProducts",
			Handler:    _Dropshipbe_GetNewProducts_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _Dropshipbe_CreateProduct_Handler,
		},
		{
			MethodName: "GetFrequentlyBoughtProducts",
			Handler:    _Dropshipbe_GetFrequentlyBoughtProducts_Handler,
		},
		{
			MethodName: "GetShop",
			Handler:    _Dropshipbe_GetShop_Handler,
		},
		{
			MethodName: "GetSocialProductVideos",
			Handler:    _Dropshipbe_GetSocialProductVideos_Handler,
		},
		{
			MethodName: "GetProductFaqs",
			Handler:    _Dropshipbe_GetProductFaqs_Handler,
		},
		{
			MethodName: "CreateProductFaq",
			Handler:    _Dropshipbe_CreateProductFaq_Handler,
		},
		{
			MethodName: "GetProductReviews",
			Handler:    _Dropshipbe_GetProductReviews_Handler,
		},
		{
			MethodName: "CreateProductReview",
			Handler:    _Dropshipbe_CreateProductReview_Handler,
		},
		{
			MethodName: "GetSliderItems",
			Handler:    _Dropshipbe_GetSliderItems_Handler,
		},
		{
			MethodName: "GetCategoryItems",
			Handler:    _Dropshipbe_GetCategoryItems_Handler,
		},
		{
			MethodName: "GetBannerItems",
			Handler:    _Dropshipbe_GetBannerItems_Handler,
		},
		{
			MethodName: "GetVideoBanner",
			Handler:    _Dropshipbe_GetVideoBanner_Handler,
		},
		{
			MethodName: "GetBlogItems",
			Handler:    _Dropshipbe_GetBlogItems_Handler,
		},
		{
			MethodName: "GetBlogBySlug",
			Handler:    _Dropshipbe_GetBlogBySlug_Handler,
		},
		{
			MethodName: "CreateNewBlog",
			Handler:    _Dropshipbe_CreateNewBlog_Handler,
		},
		{
			MethodName: "CreateOption",
			Handler:    _Dropshipbe_CreateOption_Handler,
		},
		{
			MethodName: "CreateOptionValue",
			Handler:    _Dropshipbe_CreateOptionValue_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Dropshipbe_Login_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _Dropshipbe_UploadFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _Dropshipbe_DeleteFile_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Dropshipbe_CreateOrder_Handler,
		},
		{
			MethodName: "CaptureOrder",
			Handler:    _Dropshipbe_CaptureOrder_Handler,
		},
		{
			MethodName: "HandlePaypalWebhook",
			Handler:    _Dropshipbe_HandlePaypalWebhook_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Dropshipbe_Ping_Handler,
		},
		{
			MethodName: "ChatbotMessage",
			Handler:    _Dropshipbe_ChatbotMessage_Handler,
		},
		{
			MethodName: "GetGuestToken",
			Handler:    _Dropshipbe_GetGuestToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dropshipbe.proto",
}
