// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.0
// Source: dropshipbe.proto

package dropshipbeclient

import (
	"context"

	"dropshipbe/dropshipbe"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Banner                             = dropshipbe.Banner
	BannerListResponse                 = dropshipbe.BannerListResponse
	Blog                               = dropshipbe.Blog
	BlogCategory                       = dropshipbe.BlogCategory
	BlogDetailResponse                 = dropshipbe.BlogDetailResponse
	BlogListResponse                   = dropshipbe.BlogListResponse
	CaptureOrderRequest                = dropshipbe.CaptureOrderRequest
	CaptureOrderResponse               = dropshipbe.CaptureOrderResponse
	CartItem                           = dropshipbe.CartItem
	Category                           = dropshipbe.Category
	CategoryListResponse               = dropshipbe.CategoryListResponse
	ChatbotRequest                     = dropshipbe.ChatbotRequest
	ChatbotResponse                    = dropshipbe.ChatbotResponse
	CreateNewBlogRequest               = dropshipbe.CreateNewBlogRequest
	CreateOptionRequest                = dropshipbe.CreateOptionRequest
	CreateOptionValueRequest           = dropshipbe.CreateOptionValueRequest
	CreateOrderRequest                 = dropshipbe.CreateOrderRequest
	CreateOrderResponse                = dropshipbe.CreateOrderResponse
	CreateProductFaqRequest            = dropshipbe.CreateProductFaqRequest
	CreateProductRequest               = dropshipbe.CreateProductRequest
	CreateProductReviewRequest         = dropshipbe.CreateProductReviewRequest
	DefaultRequest                     = dropshipbe.DefaultRequest
	DeleteFileRequest                  = dropshipbe.DeleteFileRequest
	DeleteFileResponse                 = dropshipbe.DeleteFileResponse
	Faq                                = dropshipbe.Faq
	FaqListResponse                    = dropshipbe.FaqListResponse
	FileData                           = dropshipbe.FileData
	Gallery                            = dropshipbe.Gallery
	GalleryListResponse                = dropshipbe.GalleryListResponse
	GetBlogBySlugRequest               = dropshipbe.GetBlogBySlugRequest
	GetFrequentlyBoughtProductsRequest = dropshipbe.GetFrequentlyBoughtProductsRequest
	GetGuestTokenRequest               = dropshipbe.GetGuestTokenRequest
	GetGuestTokenResponse              = dropshipbe.GetGuestTokenResponse
	GetInventoryRequest                = dropshipbe.GetInventoryRequest
	GetInventoryResponse               = dropshipbe.GetInventoryResponse
	GetProductBySlugRequest            = dropshipbe.GetProductBySlugRequest
	GetProductFaqsRequest              = dropshipbe.GetProductFaqsRequest
	GetProductReviewsRequest           = dropshipbe.GetProductReviewsRequest
	GetProductsByCategoryRequest       = dropshipbe.GetProductsByCategoryRequest
	GetRelatedProductsRequest          = dropshipbe.GetRelatedProductsRequest
	GetSocialProductVideoRequest       = dropshipbe.GetSocialProductVideoRequest
	LoginRequest                       = dropshipbe.LoginRequest
	LoginResponse                      = dropshipbe.LoginResponse
	Option                             = dropshipbe.Option
	OptionValue                        = dropshipbe.OptionValue
	PayPalWebhookRequest               = dropshipbe.PayPalWebhookRequest
	PriceTier                          = dropshipbe.PriceTier
	Product                            = dropshipbe.Product
	ProductListResponse                = dropshipbe.ProductListResponse
	Request                            = dropshipbe.Request
	Response                           = dropshipbe.Response
	ReviewItem                         = dropshipbe.ReviewItem
	ReviewSummary                      = dropshipbe.ReviewSummary
	ShopSearchParams                   = dropshipbe.ShopSearchParams
	Slider                             = dropshipbe.Slider
	SliderListResponse                 = dropshipbe.SliderListResponse
	UploadFileRequest                  = dropshipbe.UploadFileRequest
	UploadFileResponse                 = dropshipbe.UploadFileResponse
	UploadedFileInfo                   = dropshipbe.UploadedFileInfo
	Variant                            = dropshipbe.Variant
	VariantInventory                   = dropshipbe.VariantInventory
	VariantOption                      = dropshipbe.VariantOption
	WebhookResponse                    = dropshipbe.WebhookResponse

	Dropshipbe interface {
		// --- Inventory ---
		GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error)
		// --- Products ---
		GetProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
		GetProductBySlug(ctx context.Context, in *GetProductBySlugRequest, opts ...grpc.CallOption) (*Product, error)
		GetProductsByCategory(ctx context.Context, in *GetProductsByCategoryRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
		GetRelatedProducts(ctx context.Context, in *GetRelatedProductsRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
		GetFeaturedProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
		GetNewProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
		CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error)
		GetFrequentlyBoughtProducts(ctx context.Context, in *GetFrequentlyBoughtProductsRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
		// --- Shop Search ---
		GetShop(ctx context.Context, in *ShopSearchParams, opts ...grpc.CallOption) (*ProductListResponse, error)
		// --- Media/Galleries ---
		GetSocialProductVideos(ctx context.Context, in *GetSocialProductVideoRequest, opts ...grpc.CallOption) (*GalleryListResponse, error)
		// --- FAQs ---
		GetProductFaqs(ctx context.Context, in *GetProductFaqsRequest, opts ...grpc.CallOption) (*FaqListResponse, error)
		CreateProductFaq(ctx context.Context, in *CreateProductFaqRequest, opts ...grpc.CallOption) (*Faq, error)
		// --- Reviews ---
		GetProductReviews(ctx context.Context, in *GetProductReviewsRequest, opts ...grpc.CallOption) (*ReviewSummary, error)
		CreateProductReview(ctx context.Context, in *CreateProductReviewRequest, opts ...grpc.CallOption) (*ReviewItem, error)
		// --- UI Items (Sliders, Categories, Banners) ---
		GetSliderItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*SliderListResponse, error)
		GetCategoryItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*CategoryListResponse, error)
		GetBannerItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*BannerListResponse, error)
		GetVideoBanner(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*Banner, error)
		// --- Blogs ---
		GetBlogItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*BlogListResponse, error)
		GetBlogBySlug(ctx context.Context, in *GetBlogBySlugRequest, opts ...grpc.CallOption) (*BlogDetailResponse, error)
		CreateNewBlog(ctx context.Context, in *CreateNewBlogRequest, opts ...grpc.CallOption) (*Blog, error)
		// --- Options ---
		CreateOption(ctx context.Context, in *CreateOptionRequest, opts ...grpc.CallOption) (*Option, error)
		CreateOptionValue(ctx context.Context, in *CreateOptionValueRequest, opts ...grpc.CallOption) (*OptionValue, error)
		// --- Authentication ---
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// --- Files ---
		UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
		DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
		// --- Orders & Checkout ---
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		CaptureOrder(ctx context.Context, in *CaptureOrderRequest, opts ...grpc.CallOption) (*CaptureOrderResponse, error)
		// --- Webhooks () ---
		HandlePaypalWebhook(ctx context.Context, in *PayPalWebhookRequest, opts ...grpc.CallOption) (*WebhookResponse, error)
		// --- System ---
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		// API  Chatbot AI
		ChatbotMessage(ctx context.Context, in *ChatbotRequest, opts ...grpc.CallOption) (*ChatbotResponse, error)
		// Guest token for chatbot
		GetGuestToken(ctx context.Context, in *GetGuestTokenRequest, opts ...grpc.CallOption) (*GetGuestTokenResponse, error)
	}

	defaultDropshipbe struct {
		cli zrpc.Client
	}
)

func NewDropshipbe(cli zrpc.Client) Dropshipbe {
	return &defaultDropshipbe{
		cli: cli,
	}
}

// --- Inventory ---
func (m *defaultDropshipbe) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetInventory(ctx, in, opts...)
}

// --- Products ---
func (m *defaultDropshipbe) GetProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetProducts(ctx, in, opts...)
}

func (m *defaultDropshipbe) GetProductBySlug(ctx context.Context, in *GetProductBySlugRequest, opts ...grpc.CallOption) (*Product, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetProductBySlug(ctx, in, opts...)
}

func (m *defaultDropshipbe) GetProductsByCategory(ctx context.Context, in *GetProductsByCategoryRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetProductsByCategory(ctx, in, opts...)
}

func (m *defaultDropshipbe) GetRelatedProducts(ctx context.Context, in *GetRelatedProductsRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetRelatedProducts(ctx, in, opts...)
}

func (m *defaultDropshipbe) GetFeaturedProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetFeaturedProducts(ctx, in, opts...)
}

func (m *defaultDropshipbe) GetNewProducts(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetNewProducts(ctx, in, opts...)
}

func (m *defaultDropshipbe) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.CreateProduct(ctx, in, opts...)
}

func (m *defaultDropshipbe) GetFrequentlyBoughtProducts(ctx context.Context, in *GetFrequentlyBoughtProductsRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetFrequentlyBoughtProducts(ctx, in, opts...)
}

// --- Shop Search ---
func (m *defaultDropshipbe) GetShop(ctx context.Context, in *ShopSearchParams, opts ...grpc.CallOption) (*ProductListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetShop(ctx, in, opts...)
}

// --- Media/Galleries ---
func (m *defaultDropshipbe) GetSocialProductVideos(ctx context.Context, in *GetSocialProductVideoRequest, opts ...grpc.CallOption) (*GalleryListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetSocialProductVideos(ctx, in, opts...)
}

// --- FAQs ---
func (m *defaultDropshipbe) GetProductFaqs(ctx context.Context, in *GetProductFaqsRequest, opts ...grpc.CallOption) (*FaqListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetProductFaqs(ctx, in, opts...)
}

func (m *defaultDropshipbe) CreateProductFaq(ctx context.Context, in *CreateProductFaqRequest, opts ...grpc.CallOption) (*Faq, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.CreateProductFaq(ctx, in, opts...)
}

// --- Reviews ---
func (m *defaultDropshipbe) GetProductReviews(ctx context.Context, in *GetProductReviewsRequest, opts ...grpc.CallOption) (*ReviewSummary, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetProductReviews(ctx, in, opts...)
}

func (m *defaultDropshipbe) CreateProductReview(ctx context.Context, in *CreateProductReviewRequest, opts ...grpc.CallOption) (*ReviewItem, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.CreateProductReview(ctx, in, opts...)
}

// --- UI Items (Sliders, Categories, Banners) ---
func (m *defaultDropshipbe) GetSliderItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*SliderListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetSliderItems(ctx, in, opts...)
}

func (m *defaultDropshipbe) GetCategoryItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*CategoryListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetCategoryItems(ctx, in, opts...)
}

func (m *defaultDropshipbe) GetBannerItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*BannerListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetBannerItems(ctx, in, opts...)
}

func (m *defaultDropshipbe) GetVideoBanner(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*Banner, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetVideoBanner(ctx, in, opts...)
}

// --- Blogs ---
func (m *defaultDropshipbe) GetBlogItems(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*BlogListResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetBlogItems(ctx, in, opts...)
}

func (m *defaultDropshipbe) GetBlogBySlug(ctx context.Context, in *GetBlogBySlugRequest, opts ...grpc.CallOption) (*BlogDetailResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetBlogBySlug(ctx, in, opts...)
}

func (m *defaultDropshipbe) CreateNewBlog(ctx context.Context, in *CreateNewBlogRequest, opts ...grpc.CallOption) (*Blog, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.CreateNewBlog(ctx, in, opts...)
}

// --- Options ---
func (m *defaultDropshipbe) CreateOption(ctx context.Context, in *CreateOptionRequest, opts ...grpc.CallOption) (*Option, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.CreateOption(ctx, in, opts...)
}

func (m *defaultDropshipbe) CreateOptionValue(ctx context.Context, in *CreateOptionValueRequest, opts ...grpc.CallOption) (*OptionValue, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.CreateOptionValue(ctx, in, opts...)
}

// --- Authentication ---
func (m *defaultDropshipbe) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// --- Files ---
func (m *defaultDropshipbe) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.UploadFile(ctx, in, opts...)
}

func (m *defaultDropshipbe) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.DeleteFile(ctx, in, opts...)
}

// --- Orders & Checkout ---
func (m *defaultDropshipbe) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultDropshipbe) CaptureOrder(ctx context.Context, in *CaptureOrderRequest, opts ...grpc.CallOption) (*CaptureOrderResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.CaptureOrder(ctx, in, opts...)
}

// --- Webhooks () ---
func (m *defaultDropshipbe) HandlePaypalWebhook(ctx context.Context, in *PayPalWebhookRequest, opts ...grpc.CallOption) (*WebhookResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.HandlePaypalWebhook(ctx, in, opts...)
}

// --- System ---
func (m *defaultDropshipbe) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// API  Chatbot AI
func (m *defaultDropshipbe) ChatbotMessage(ctx context.Context, in *ChatbotRequest, opts ...grpc.CallOption) (*ChatbotResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.ChatbotMessage(ctx, in, opts...)
}

// Guest token for chatbot
func (m *defaultDropshipbe) GetGuestToken(ctx context.Context, in *GetGuestTokenRequest, opts ...grpc.CallOption) (*GetGuestTokenResponse, error) {
	client := dropshipbe.NewDropshipbeClient(m.cli.Conn())
	return client.GetGuestToken(ctx, in, opts...)
}
